### ISSUE TITLE
Add loading/processing indicators

### ISSUE THREAD

**Issue by rschristian** [mutoe/preact-realworld-example-app#29]
(Just providing this as a way of keeping track of things, especially if I can't find time to implement myself)

A few different items don't provide any indication of work being done, which is problematic as the RealWorld API we hit is dreadfully slow. Users will hit the login button and not know if anything is actually happening, and on the homepage will be met by "No articles are here... yet" until the article fetch actually finishes. 

We need to add loading indicators a) as a UX thing and b) to stave off the defaults (i.e., "No articles found") in a few locations

**Comment by mutoe** [comment]
I think we don't need to consider the UX for real-world example app. Our "user" is the Preact developer but not a conduit user, right?

**Comment by rschristian** [comment]
Usually I'd agree, but trying to use this site is quite painful at the moment.

It's off enough where the app feels sorta broken, due to the hideously slow API response.

**Comment by mutoe** [comment]
Forbearance, it is just a free server, lol

**Comment by rschristian** [comment]
Oh, of course. It's massively helpful having that server that we can ping and be sure follows the spec 100%.

It's just slow enough where not having loading indicators and the like switch from UX to general usability, as I often think I've broken something with how long some of the delays are between request and population. Users loading this will probably be even less forgiving, and assume this repo is broken.

**Comment by mutoe** [comment]
So can we add a loading status for submit button disabled props?

https://github.com/mutoe/preact-realworld-example-app/blob/5ea8f0fd3f9860cc9be0bf6959013dd78cbcb2cc/src/pages/Login.tsx#L73

**Comment by rschristian** [comment]
Something along those lines, yeah. And anywhere we fetch data.
