### ISSUE TITLE
Homepage should not redirect to login

### ISSUE THREAD

**Issue by benmccann** [mutoe/preact-realworld-example-app#4]
Whenever I visit https://mutoe.github.io/preact-realworld-example-app/ it redirects me to https://mutoe.github.io/preact-realworld-example-app/#/login. This does not happen in the implementations for any other languages/frameworks. It makes it hard to compare to the others since it behaves so differently

**Comment by mutoe** [comment]
Thanks for your reply, I'm going to check it :)

**Comment by mutoe** [comment]
fixed
