### ISSUE TITLE
Consider code splitting

### ISSUE THREAD

**Issue by benmccann** [mutoe/preact-realworld-example-app#6]
The main js file is about 80kb, which seems quite large. Partially this is because source maps are enabled (https://github.com/mutoe/preact-realworld-example-app/issues/5). However, I also suspect that all components are being bundled into a single JS file instead of being split based on the route

**Comment by mutoe** [comment]
I tried lazy loading of components but failed. If anyone has a better way, PR is welcome :)

**Comment by rschristian** [comment]
@mutoe Do you happen to know what the rules are for build tools? If we were to switch this over to [wmr](https://github.com/preactjs/wmr) I imagine we'd see quite the improvement, not to mention being able to shave off a lot of the bulk of tooling.

Might write up a demo PR.

Edit: We could also simplify this a lot. It has way more going on in it than every other app. Might scare off some users.

**Comment by rschristian** [comment]
As of #30 there is full route splitting.

~25kb for the home page to load, with 20kb of that being shared resources. ~32kb for entire application.

Still definitely some room to cut. Replacing Zustand with a smaller or Preact focused lib would allow for a sizeable reduction. Zustand is the only lib that requires `preact/compat`, and together they make up 17.3% of the bundle on their own.
