### ISSUE TITLE
Consider a WMR-based rewrite

### ISSUE THREAD

**Issue by rschristian** [mutoe/preact-realworld-example-app#8]
Hello! Left a comment on that other thread but I think this would be better to split out.

Would you maybe be up for reviewing a bit of a rewrite? Currently this repo is quite "busy" compared to the others and I think, because of this, it doesn't necessarily paint Preact in the best light. It also adds quite a bit of weight.

Step 1 would be to remove all the extra tooling. We really don't need a dozen eslint rules or git hooks. They don't add anything to showing off Preact.

We can replace all the build tooling with WMR, a super fast and light tool from the Preact team. 

Also can get rid of all the tests. Very few other examples have them so I don't think it worth having?

And while I do love TS, I have to wonder if that's the right move here for a showcase? The repo title doesn't include "TS" so I think JS would be better? I'm not sold on this idea, as, personally, I do vastly prefer TS but I'm thinking JS might be better for this type of use. 

We can also look at replacing some functionality. Using preact-iso, we can swap out Preact-Router for a much better and modern alternative (also built by the Preact team). 

Swapping out any `fetch()`'s with Redaxios could be another interesting avenue. Axios API without the bundle size cost. 

I'm entirely willing to put this all together, provided you'd be willing to review. I'd like to help out and get this a bit more popular if I can.

**Comment by mutoe** [comment]
@rschristian  Thanks for your suggestion. I think the ESLint and TS are just for development experience, and it doesn't affect the final runtime result. So I don't think we need to remove the ESLint and Git hooks. TS is the same.

As for WMR, I am not sure what it is, if you can, you can use this approach (if it is officially recommended), and I will merge your PR.

For the fetch or not, I also think that what kind of request library is used will not impact how to use Preact.

Finally, for testing, I think it is necessary to provide test examples. Although you think it is unnecessary, unit testing is still an essential part of some large projects. The significance of the Realworld project is to provide some examples for beginners.

So I suggest that we only need to replace the build tool. What do you think?

**Comment by rschristian** [comment]
Well the ultimate goal here is to do a bit more of marketing alongside providing some code examples. I know I still come to real world to get quick glimpses of what a language or tool is all about.

Currently, the "busyness" of this really isn't helping to sell Preact. Just look at the package files ([react-redux](https://github.com/gothinkster/react-redux-realworld-example-app/blob/master/package.json), [preact](https://github.com/mutoe/preact-realworld-example-app/blob/master/package.json)). It's absolutely night and day. 

What we need to do is cut down on all that config and just get it out. It's not relevant, and doesn't end up adding anything. We want a clear and concise application here. 

TS, similarly, is more complicated, and we're looking to appeal to the lowest common denominator which is JS users/usage. Having code examples only in TS doesn't help those who are looking for a quick overview of the JS. 

> For the fetch or not, I also think that what kind of request library is used will not impact how to use Preact.

Totally agree, it won't, however, the React-Redux template has `superagent` for example, and getting the very popular Axios API for none of the cost can just be a nice addition. Minor detail either way.

> Although you think it is unnecessary, unit testing is still an essential part of some large projects

I do not think testing is unnecessary, I just didn't think it was necessary for this use, though, as I've poked around more, it seems my initial assertion (that most do not have tests) is totally incorrect! Just got totally lucking (unlucky?) with my random selections previously as most did not. So totally agree, definitely keep the tests. Sorry!

Ultimately I'd like to avoid creating a new example, using the more officially sanctioned tools/methods, though obviously I still can if you'd prefer to keep this around.

**Comment by mutoe** [comment]
For the redux, I will not consider it. It is too heavy, and we can use context instead of it.

I will replace the build tool with wmr this weekend. If you are working on this, you can tell me, and I will do another work(refactor store context).

For the TS, I think we can create another branch to display the JS version and Testing-library?

**Comment by rschristian** [comment]
Sorry if anything I said suggested adding Redux; I totally agree, it's way too heavy and doesn't make sense for the use case. Just meant to more closely match (the very popular) Real World template project React-Redux.

I do have a start, can continue to run through and get it up quickly. I'll hopefully get a draft up before the weekend. 

Branches are a pretty good idea.

**Comment by mutoe** [comment]
@rschristian Good jobs! Waiting for your PR :)

**Comment by rschristian** [comment]
Closing, figure keeping the issue open has no real value at this point.
